# Generated by Django 5.1.6 on 2025-02-25 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Credits',
            new_name='Credit',
        ),
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
        migrations.RenameModel(
            old_name='Plans',
            new_name='Plan',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
